### ISSUE TITLE
Hi why am i being notified for this project - please remove me cause I am not able to unsubscribe.

### ISSUE THREAD

**Issue by cyazbek** [CiscoDevNet/finesse-sample-code#7]

**Comment by cyazbek** [comment]
![image](https://user-images.githubusercontent.com/7517870/52059899-12c86f80-2539-11e9-9192-d69a83285fe8.png)

**Comment by dekwan** [comment]
Hi,

I see that you are following the repo
![image](https://user-images.githubusercontent.com/17052491/52191130-f6a62600-27f7-11e9-9277-e561feae894e.png)

It seems like you might have another github account which is why you were getting notifications. If you would no longer like to receive notifications for this repo, please log into the other account and unsubscribe or change your notifications to "Ignoring".

Thanx,
Denise
